#!/bin/sh

[ -x "$(command -v lvim)" ] && alias vim="lvim" vimdiff="lvim -d"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best --audio-format mp3 --restrict-filenames --xattrs --embed-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	g="git" \
  gcm="git commit -am"\
  cdt="$TERMINAL &>/dev/null & disown" \
	f="rga-fzf" \
  kt="kitty & disown" \
  ssh="kitty +kitten ssh"
